name: PetTracker
options:
  bundleIdPrefix: com.pettracker
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
  developmentLanguage: en
  xcodeVersion: "26.1"
  
configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

packages:
  PetTrackerFeature:
    path: PetTrackerPackage

targets:
  PetTracker:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: PetTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pettracker.PetTracker
        PRODUCT_NAME: PetTracker
        INFOPLIST_FILE: PetTracker/Info.plist
        CODE_SIGN_ENTITLEMENTS: PetTracker/PetTracker.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_PREVIEWS: true
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    dependencies:
      - package: PetTrackerFeature

  "PetTracker Watch App":
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: "PetTracker Watch App Extension"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pettracker.PetTracker.watchkitapp
        PRODUCT_NAME: "PetTracker Watch App"
        INFOPLIST_FILE: "PetTracker Watch App Extension/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "PetTracker Watch App Extension/PetTracker Watch App Extension.entitlements"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_PREVIEWS: true
        SKIP_INSTALL: false
        WATCHOS_DEPLOYMENT_TARGET: "26.0"
    dependencies:
      - package: PetTrackerFeature
